//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BWChess.rc
//
#define IDC_AVAIL_MEM                   101
#define IDD_BWCHESS_DIALOG              102
#define IDC_PHYSICAL_MEM                102
#define IDC_AVAIL_VIRTUAL_MEM           103
#define IDC_CPU                         104
#define IDC_OS                          105
#define IDC_VERSION                     106
#define IDD_ABOUTDLG1                   107
#define IDM_ABOUT                       108
#define IDR_MENU_CHINESE                122
#define IDR_MAINFRAME                   128
#define IDR_ACC                         128
#define IDDIB_BLACK                     129
#define IDC_BLACK_HAND                  130
#define IDDIB_BOARD                     130
#define IDC_WHITE_HAND                  131
#define IDDIB_MASK                      131
#define IDD_SETTING1                    131
#define IDDIB_WHITE                     132
#define IDI_SETTING                     132
#define IDR_MENU_CONTEXT_CHINESE        133
#define IDI_RULE                        133
#define IDSOUND_BLACKWIN                135
#define IDD_HOWTO1                      136
#define IDSOUND_ERROR                   136
#define IDD_RECORD1                     137
#define IDSOUND_GOODBYE                 137
#define IDSOUND_NEWGAME                 138
#define IDD_SEC                         138
#define IDSOUND_PUTSTONE                139
#define IDD_CONFIRMSEC                  139
#define IDSOUND_UNDO                    140
#define IDSOUND_USERWIN                 141
#define IDSOUND_COMPUTERWIN             142
#define IDSOUND_WELCOME                 143
#define IDDIB_CANPLACE1                 143
#define IDSOUND_WHITEWIN                144
#define IDDIB_CANPLACE2                 144
#define IDI_OPEN                        145
#define IDDIB_EMPTY                     145
#define IDDIB_F10_1                     146
#define IDDIB_F10_10                    147
#define IDDIB_F10_2                     148
#define IDI_RESET                       149
#define IDDIB_F10_3                     149
#define IDC_HAND                        150
#define IDDIB_F10_4                     150
#define IDDIB_F10_5                     151
#define IDDIB_F10_6                     152
#define IDDIB_F10_7                     153
#define IDDIB_F10_8                     154
#define IDDIB_F10_9                     155
#define IDD_MESSAGE1                    156
#define IDDIB_F1_1                      156
#define IDI_QUERY                       157
#define IDDIB_F1_10                     157
#define IDD_MESSAGE2                    158
#define IDDIB_F9_1                      158
#define IDDIB_F1_3                      159
#define IDDIB_F1_4                      160
#define IDI_MORE                        161
#define IDDIB_F1_5                      161
#define IDI_HERO                        162
#define IDDIB_F1_6                      162
#define IDI_HOWTO                       163
#define IDDIB_F1_7                      163
#define IDI_CANCEL                      164
#define IDDIB_F1_8                      164
#define IDI_RECORD                      165
#define IDDIB_F1_9                      165
#define IDI_SHANKHAND                   166
#define IDDIB_F2_1                      166
#define IDDIB_F3_1                      167
#define IDDIB_F4_1                      168
#define IDDIB_F5_1                      169
#define IDDIB_F6_1                      170
#define IDDIB_F7_1                      171
#define IDDIB_F8_1                      172
#define IDDIB_F1_2                      173
#define IDDIB_F9_10                     174
#define IDDIB_F3_10                     175
#define IDDIB_F4_10                     176
#define IDDIB_F5_10                     177
#define IDDIB_F6_10                     178
#define IDDIB_F7_10                     179
#define IDDIB_F8_10                     180
#define IDDIB_F2_10                     181
#define IDI_SEC0                        183
#define IDI_SEC1                        184
#define IDD_DEMO                        185
#define IDD_NETPLAY                     186
#define IDI_OPENFILE                    187
#define IDI_HELP2                       189
#define IDI_NETPLAY                     190
#define IDDIB_CURBLACK                  191
#define IDDIB_CURWHITE                  192
#define IDD_BEST1                       513
#define IDD_SETUPDLG1                   514
#define IDC_SOUNDON                     1000
#define IDC_DYNAMIC                     1001
#define IDC_TOPMOST                     1002
#define IDC_PEEPOFTEN                   1004
#define IDC_LISTINFO                    1005
#define IDC_INFO                        1006
#define IDC_SHOWDYNAMIC                 1008
#define IDC_RADIO_WITHCOMPUTER          1009
#define IDC_TIME_CHINESE0               1009
#define IDC_RADIO_2PLAYER               1010
#define IDC_ADDSEC                      1010
#define IDC_RADIO_YOU_FIRST             1013
#define IDS_SINGLE_COMPUTER_CHINESE     1013
#define IDC_RADIO_COMPUTER_FIRST        1014
#define IDS_SINGLE_USER_CHINESE         1014
#define IDC_SEC1                        1014
#define IDS_DOUBLE_CHINESE              1015
#define IDC_SEC2                        1015
#define IDS_DOUBLE_NOLIMIT_CHINESE      1015
#define IDC_TOTAL_SPACE                 1016
#define IDC_FREE_SPACE                  1017
#define IDC_BNUM                        1017
#define IDC_WNUM                        1018
#define IDC_DYSTATIC                    1018
#define IDC_TIME_CHINESE                1019
#define IDS_NOSOUND_CHINESE             1019
#define IDC_SEC                         1019
#define IDC_NONEEDTIME                  1020
#define IDS_TITLE_CHINESE               1021
#define IDC_SPINNUM                     1021
#define IDC_TIMENUM                     1022
#define IDC_SEC3                        1023
#define IDS_BLACKWIN_CHINESE            1024
#define IDC_RULES                       1024
#define IDC_EDIT1                       1026
#define IDS_WHITEWIN_CHINESE            1026
#define IDC_CONTENT                     1026
#define IDC_EDIT2                       1027
#define IDS_TOTAL_CHINESE               1027
#define IDC_TITLE                       1027
#define IDC_EDIT3                       1028
#define IDC_HUNDO                       1028
#define IDC_EDIT4                       1029
#define IDC_HHINT                       1029
#define IDC_EDIT5                       1030
#define IDC_HOPEN                       1030
#define IDC_EDIT6                       1031
#define IDC_HSAVE                       1031
#define IDC_EDIT7                       1032
#define IDC_HSAVEINFO                   1032
#define IDC_RESTARTCOUNT                1033
#define IDC_HSETTING                    1033
#define IDC_INFORMATION                 1034
#define IDC_EDIT8                       1034
#define IDC_HSEC                        1034
#define IDC_ADDRESS                     1035
#define IDC_EDIT9                       1035
#define IDC_HLIMIT                      1035
#define IDC_MORE                        1036
#define IDC_RULE                        1036
#define IDC_HHERO                       1036
#define IDC_ADVANCE                     1037
#define IDC_B1                          1037
#define IDC_SKILL1                      1038
#define IDC_B2                          1038
#define IDC_SKILL2                      1039
#define IDC_B3                          1039
#define IDC_SKILL3                      1040
#define IDC_W1                          1040
#define IDS_BEGINNER_CHINESE            1041
#define IDC_W2                          1041
#define IDC_W3                          1042
#define IDS_INTERMEDIATE_CHINESE        1043
#define IDC_SPEED1                      1043
#define IDS_EXPERT_CHINESE              1044
#define IDC_SPEED2                      1044
#define IDC_SPEED3                      1045
#define IDC_HNETPLAY                    1046
#define IDC_HDEMO                       1047
#define IDC_HPEEP                       1049
#define IDC_IPADDRESS                   1053
#define IDC_SERVER                      1054
#define IDC_CLIENT                      1055
#define IDC_CONNECT                     1056
#define IDC_NAME                        1057
#define IDC_PORT                        1058
#define IDC_ISFILE                      1059
#define IDC_FILEPATH                    1060
#define IDC_BROWNS                      1061
#define IDC_MOREN                       1062
#define IDS_COLOR_LESS_CHINESE          1063
#define IDC_HELP0                       1063
#define IDS_END_CHINESE                 1064
#define IDS_TIE_CHINESE                 1065
#define IDS_BLACK_ONEPLACE_CHINESE      1066
#define IDC_HELP1                       1066
#define IDS_WHITE_ONEPLACE_CHINESE      1067
#define IDS_BLACK_NOPLACE_CHINESE       1068
#define IDS_WHITE_NOPLACE_CHINESE       1069
#define IDC_SAMCHK                      1069
#define IDS_COMPUTERWIN2_CHINESE        1070
#define IDC_RADIOSAM                    1070
#define IDS_USERWIN1_CHINESE            1071
#define IDS_USER_NOPLACE_CHINESE        1072
#define IDS_COMPUTER_NOPLACE_CHINESE    1073
#define IDS_USER_ONEPLACE_CHINESE       1074
#define IDS_SURETORECOUNT_CHINESE       1079
#define IDS_CANNOT_UNDO1_CHINESE        1082
#define IDS_COMPUTERWIN1_CHINESE        1083
#define IDS_COMPUTERWIN0_CHINESE        1084
#define IDS_USERWIN2_CHINESE            1085
#define IDC_PROMPT                      1085
#define IDS_USERWIN0_CHINESE            1086
#define IDS_EDITION                     1087
#define IDS_AUTHOR                      1088
#define IDS_ABORT                       1089
#define IDS_LEAVE_END                   1090
#define IDS_LEAVE_NOEND                 1091
#define IDS_RULE_TITLE                  1092
#define IDS_RULE_CONTENT                1093
#define IDS_SBLACK                      1094
#define IDS_SWHITE                      1095
#define IDS_TIE                         1096
#define IDS_OPENERROR                   1097
#define IDS_OPENERROR1                  1097
#define IDS_MORETHANTHREE_CHINESE       1098
#define IDS_OPENERROR2                  1099
#define IDS_ADDSEC                      1100
#define IDS_CONSEC                      1101
#define IDS_SEC_ERR1                    1102
#define IDS_SEC_ERR2                    1103
#define IDS_SEC_ERR3                    1104
#define IDS_SEC_ERR0                    1105
#define IDS_BLACK_LIMIT                 1106
#define IDS_WHITE_LIMIT                 1107
#define IDS_HAVESEC                     1108
#define IDS_NOSEC                       1109
#define IDS_DOUBLE_LIMIT_CHINESE        1110
#define IDS_HRULES1                     1111
#define IDS_HRULES0                     1112
#define IDS_HMIJUE0                     1113
#define IDS_HMIJUE1                     1114
#define IDS_HOPEN1                      1115
#define IDS_HUNDO1                      1116
#define IDS_HSAVE1                      1117
#define IDS_HOPEN0                      1118
#define IDS_HUNDO0                      1119
#define IDS_HSAVE0                      1120
#define IDS_HSETTING0                   1121
#define IDS_HHINT0                      1122
#define IDS_HSAVEINFO0                  1123
#define IDS_HSETTING1                   1124
#define IDS_HHINT1                      1125
#define IDS_HSAVEINFO1                  1126
#define IDS_HHERO0                      1127
#define IDS_HSEC0                       1128
#define IDS_HLIMIT0                     1129
#define IDS_HHERO1                      1130
#define IDS_HSEC1                       1131
#define IDS_HLIMIT1                     1132
#define IDS_DEMOTITLE0                  1133
#define IDS_DEMOTITLE1                  1134
#define IDS_DEMO_TITLE_11               1135
#define IDS_DEMO_TITLE_12               1136
#define IDS_DEMO_TITLE_13               1137
#define IDS_DEMO_TITLE_21               1138
#define IDS_DEMO_TITLE_22               1139
#define IDS_DEMO_TITLE_23               1140
#define IDS_DEMO_TITLE_31               1141
#define IDS_DEMO_TITLE_32               1142
#define IDS_DEMO_TITLE_33               1143
#define IDS_HPEEP0                      1144
#define IDS_HPEEP1                      1145
#define IDS_HNETPLAY0                   1146
#define IDS_HNETPLAY1                   1147
#define IDS_HDEMO0                      1148
#define IDS_HDEMO1                      1149
#define IDS_OPENERROR3                  1150
#define IDS_OPENERROR4                  1151
#define IDS_REPLAY0                     1152
#define IDS_REPLAY1                     1153
#define IDS_ERROR_NOFILE                1154
#define IDS_ERROR_ALREADY_EXIST         1155
#define IDM_NEW                         32769
#define IDM_EXIT                        32770
#define IDM_UNDO                        32771
#define IDM_HOWTO                       32772
#define IDM_SETTING                     32773
#define IDM_SAVE                        32774
#define IDM_OPEN                        32775
#define IDM_BEST                        32776
#define IDM_SAVEINFO                    32777
#define IDM_HINT                        32778
#define IDM_DEMO                        32779
#define IDM_CANPLACE                    32780
#define IDM_NETPLAY                     32781
#define IDM_REPLAY                      32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
